# Generated by Django 5.1.6 on 2025-04-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_vehicle_image_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(default='Unknown Brand', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_name',
            field=models.CharField(default='Unknown Model', max_length=100),
        ),
    ]
