# Generated by Django 5.2 on 2025-04-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_alter_cartitem_user_alter_cartitem_vehicle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
